# Generated by Django 4.0.6 on 2022-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cart_razorpay_order_id_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
