# Generated by Django 4.0.6 on 2022-08-08 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a9eeef6-3eb2-4023-a5dc-21a67d2712ce'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a9eeef6-3eb2-4023-a5dc-21a67d2712ce'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a9eeef6-3eb2-4023-a5dc-21a67d2712ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
