# Generated by Django 4.0.6 on 2022-08-08 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_uid_alter_productcategory_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fdf2927b-62c8-4733-9dc2-8ee37d75af6b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fdf2927b-62c8-4733-9dc2-8ee37d75af6b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fdf2927b-62c8-4733-9dc2-8ee37d75af6b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
